import * as vscode from 'vscode';
export const scenarioMap = {
  pivotCharts: (picked: boolean): vscode.QuickPickItem[] => [
    'area',
    'bar',
    'barInPolar',
    'bubble',
    'column',
    'combined',
    'dataTable',
    'donut',
    'filledRadar',
    'floorPlan',
    'funnel',
    'gauge',
    'indicator',
    'KPI',
    'kpiMatrix',
    'line',
    'map',
    'percentStackedArea',
    'percentStackedBar',
    'percentStackedColumn',
    'pie',
    'pivotTable',
    'radar',
    'radialStackedBar',
    'rangeArea',
    'rangeBar',
    'rangeColumn',
    'rose',
    'scatter',
    'stackedArea',
    'stackedBar',
    'stackedBarInPolar',
    'stackedColumn',
    'sunburst',
    'treeMap',
  ].map(i => ({ label: i, picked })),
  richEditor: (picked: boolean): vscode.QuickPickItem[] => [
    'richEditor',
  ].map(i => ({ label: i, picked })),
  picture: (picked: boolean): vscode.QuickPickItem[] => [
    'picture',
  ].map(i => ({ label: i, picked })),
  slicer: (picked: boolean): vscode.QuickPickItem[] => [
    'label',
    'tree',
    'comboBox',
    'dateRange',
    'dataRange',
    'relativeDate',
  ].map(i => ({ label: i, picked })),
  container: (picked: boolean): vscode.QuickPickItem[] => [
    'container',
  ].map(i => ({ label: i, picked })),
  tabContainer: (picked: boolean): vscode.QuickPickItem[] => [
    'tabContainer',
  ].map(i => ({ label: i, picked })),
  webContent: (picked: boolean): vscode.QuickPickItem[] => [
    'webContent',
  ].map(i => ({ label: i, picked })),
  spreadChart: (picked: boolean): vscode.QuickPickItem[] => [
    'spreadChart',
  ].map(i => ({ label: i, picked })),
};